exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('players').del()
    .then(function() {
      // Inserts seed entries
      return knex('players').insert([
        { first_name: 'LeBron', last_name: 'James', team_id: 1, jersey: 23, position: 'SF', points: 27.1, steals: 1.6, assists: 7.1, blocks: 0.8, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/LeBron_James_%2831944491583%29.jpg/220px-LeBron_James_%2831944491583%29.jpg' },
        { first_name: 'Kevin', last_name: 'Love', team_id: 1, jersey: 0, position: 'PF', points: 18.4, steals: 0.7, assists: 2.3, blocks: 0.5, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Kevin_Love_%2831915891514%29.jpg/240px-Kevin_Love_%2831915891514%29.jpg' },
        { first_name: 'Isaiah', last_name: 'Thomas', team_id: 1, jersey: 3, position: 'PG', points: 19.0, steals: 1.0, assists: 5.1, blocks: 0.1, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Isaiah_Thomas_%2834300573362%29.jpg/220px-Isaiah_Thomas_%2834300573362%29.jpg' },
        { first_name: 'Dwayne', last_name: 'Wade', team_id: 1, jersey: 9, position: 'PG', points: 22.8, steals: 2.3, assists: 5.6, blocks: 0.9, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Dwyane_Wade_e1.jpg/275px-Dwyane_Wade_e1.jpg' },
        { first_name: 'Kyle', last_name: 'Korver', team_id: 1, jersey: 26, position: 'SG', points: 9.9, steals: 0.7, assists: 1.8, blocks: 0.3, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Korver_croppd.jpg/220px-Korver_croppd.jpg' },
        { first_name: 'Stephen', last_name: 'Curry', team_id: 2, jersey: 30, position: 'PG', points: 23.1, steals: 1.8, assists: 6.8, blocks: 0.2, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Stephen_Curry_dribbling_2016_%28cropped%29.jpg/220px-Stephen_Curry_dribbling_2016_%28cropped%29.jpg' },
        { first_name: 'Klay', last_name: 'Thompson', team_id: 2, jersey: 11, position: 'SG', points: 19.2, steals: 0.9, assists: 2.3, blocks: 0.5, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Klay_Thompson_vs._Jared_Dudley_%28cropped%29.jpg/260px-Klay_Thompson_vs._Jared_Dudley_%28cropped%29.jpg' },
        { first_name: 'Draymond', last_name: 'Green', team_id: 2, jersey: 23, position: 'PF', points: 9.2, steals: 1.4, assists: 4.4, blocks: 1.1, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Draymond_Green_against_Washington_%28cropped%29.jpg/220px-Draymond_Green_against_Washington_%28cropped%29.jpg' },
        { first_name: 'Nick', last_name: 'Young', team_id: 2, jersey: 6, position: 'SG', points: 11.6, steals: 0.6, assists: 1.0, blocks: 0.2, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Nick_Young_Lakers.jpg/220px-Nick_Young_Lakers.jpg' },
        { first_name: 'Kevin', last_name: 'Durant', team_id: 2, jersey: 35, position: 'SF', points: 27.1, steals: 1.2, assists: 3.9, blocks: 1.1, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Kevin_Durant_-_TechCrunch_Disrupt_SF_2017_-_Day_2_%2836517991413%29.jpg/220px-Kevin_Durant_-_TechCrunch_Disrupt_SF_2017_-_Day_2_%2836517991413%29.jpg' },
        { first_name: 'Carmelo', last_name: 'Anthony', team_id: 3, jersey: 7, position: 'SF', points: 24.4, steals: 2.9, assists: 3.1, blocks: 1.0, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Carmelo_Anthony_Nov_2013.jpg/250px-Carmelo_Anthony_Nov_2013.jpg' },
        { first_name: 'Russell', last_name: 'Westbrook', team_id: 3, jersey: 0, position: 'PG', points: 22.9, steals: 1.7, assists: 8.1, blocks: 0.3, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Russell_Westbrook_%2832077032673%29.jpg/220px-Russell_Westbrook_%2832077032673%29.jpg' },
        { first_name: 'Paul', last_name: 'George', team_id: 3, jersey: 13, position: 'SF', points: 18.4, steals: 1.7, assists: 3.1, blocks: 0.4, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Paul_George_Pacers.jpg/260px-Paul_George_Pacers.jpg' },
        { first_name: 'Steven', last_name: 'Adams', team_id: 3, jersey: 12, position: 'C', points: 8.3, steals: 0.7, assists: 0.8, blocks: 1.0, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Steven_Adams_%2832049572304%29.jpg/220px-Steven_Adams_%2832049572304%29.jpg' },
        { first_name: 'Raymond', last_name: 'Felton', team_id: 3, jersey: 2, position: 'PG', points: 11.6, steals: 1.2, assists: 5.5, blocks: 0.2, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Raymond_Felton_Knicks_cropped.jpg/220px-Raymond_Felton_Knicks_cropped.jpg' },
        { first_name: 'Chris', last_name: 'Paul', team_id: 4, jersey: 3, position: 'PG', points: 18.7, steals: 2.3, assists: 9.8, blocks: 0.1, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Chris_Paul_dribbling_20131118_Clippers_v_Grizzles.jpg/275px-Chris_Paul_dribbling_20131118_Clippers_v_Grizzles.jpg' },
        { first_name: 'James', last_name: 'Harden', team_id: 4, jersey: 13, position: 'PG', points: 22.7, steals: 1.5, assists: 5.9, blocks: 0.5, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/James_Harden_Rockets_cropped.jpg/220px-James_Harden_Rockets_cropped.jpg' },
        { first_name: 'Eric', last_name: 'Gordon', team_id: 4, jersey: 10, position: 'SG', points: 16.8, steals: 1.0, assists: 3.1, blocks: 0.3, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Eric_Gordon_%2830550862210%29_%28cropped%29.jpg/260px-Eric_Gordon_%2830550862210%29_%28cropped%29.jpg' },
        { first_name: 'Gerald', last_name: 'Green', team_id: 4, jersey: 14, position: 'SG', points: 9.7, steals: 0.5, assists: 1.0, blocks: 0.3, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Gerald_Green_2017_v_Wizards.jpg/220px-Gerald_Green_2017_v_Wizards.jpg' },
        { first_name: 'Trevor', last_name: 'Ariza', team_id: 4, jersey: 1, position: 'SG', points: 10.5, steals: 1.5, assists: 2.1, blocks: 0.3, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Trevor_Ariza_Wizards.jpg/220px-Trevor_Ariza_Wizards.jpg' },
        { first_name: 'Anthony', last_name: 'Davis', team_id: 5, jersey: 23, position: 'PF', points: 22.8, steals: 1.3, assists: 1.8, blocks: 2.3, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Anthony_Davis_12711093105.jpg/220px-Anthony_Davis_12711093105.jpg' },
        { first_name: 'Demarcus', last_name: 'Cousins', team_id: 5, jersey: 0, position: 'PF', points: 21.5, steals: 1.4, assists: 3.2, blocks: 1.2, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/DeMarcus_Cousins_Kings_December_2012.jpg/250px-DeMarcus_Cousins_Kings_December_2012.jpg' },
        { first_name: 'Rajon', last_name: 'Rondo', team_id: 5, jersey: 9, position: 'PG', points: 10.5, steals: 1.8, assists: 8.4, blocks: 0.1, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Rajon_Rondo_Media_Day.jpg/220px-Rajon_Rondo_Media_Day.jpg' },
        { first_name: 'Jrue', last_name: 'Holiday', team_id: 5, jersey: 11, position: 'PG', points: 14.7, steals: 1.5, assists: 6.2, blocks: 0.4, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/20140101_Jrue_Holiday.JPG/220px-20140101_Jrue_Holiday.JPG' },
        { first_name: 'Ian', last_name: 'Clark', team_id: 5, jersey: 2, position: 'SG', points: 4.7, steals: 0.4, assists: 1.0, blocks: 0.1, img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Ian_Clark_2017.jpg/220px-Ian_Clark_2017.jpg' },
      ]);
    });
};